### ISSUE TITLE
CRIAR CONTA DE USUÁRIO

### ISSUE THREAD

**Issue by steinjonathan** [steinjonathan/unitunes#6]
Usuário que não possui uma conta se cadastra podendo assim ter o acesso ao uniTunes.

Fluxo Básico

O acadêmico clica em “Criar conta de usuário”.
O sistema abre a tela com o formulário de cadastro com os seguintes campos:
- Primeiro nome;
- Último nome;
- Email (usuário);
- Senha;
- Confirmação da senha.

O acadêmico preenche os campos do formulário e clica em “Cadastrar”;
O sistema valida as informações e cadastra o acadêmico; [RN01][RN02]
O sistema redireciona o usuário para a tela inicial do sistema.

**Comment by oswaldoacauan** [comment]
Feito
