### ISSUE TITLE
AUTENTICAR USUÁRIO

### ISSUE THREAD

**Issue by steinjonathan** [steinjonathan/unitunes#8]
O usuário pode acessar sua biblioteca de mídias.

Fluxo Básico
O usuário informa o email e senha e clica em “Entrar”. [FA01]
O sistema valida o email e a senha informados. [RN02]
O sistema redireciona o usuário para a página inicial do uniTunes. [RN19]

**Comment by oswaldoacauan** [comment]
Feito.
